In [5]:
import pandas as pd
import numpy as np

means_data = pd.read_csv("Data/mean_matrix.csv")
covariance_matrix = pd.read_csv("Data/variance_matrix_30.csv")
means = np.array(means_data[["formue_2018_Mean", "pension_2018_Mean", "hourly_salary_Mean"]])[0]
covariance_matrix.set_index('_NAME_', inplace=True)
covar_array = np.array(covariance_matrix.loc[["formue_2018", "pension_2018", "hourly_salary"], ["formue_2018", "pension_2018", "hourly_salary"]].values)


In [6]:
covar_array

array([[1.46911229e+11, 6.02511839e+09, 4.95039002e+06],
       [6.02511839e+09, 7.82006946e+09, 1.72700247e+06],
       [4.95039002e+06, 1.72700247e+06, 4.69833979e+03]])

In [14]:
means_data = pd.read_csv("Data/mean_matrix.csv")
covariance_matrix = pd.read_csv("Data/variance_matrix.csv")
means = np.array(means_data[["formue_2018_Mean", "pension_2018_Mean", "yearly_salary_Mean"]])[0]

In [15]:
covar_array = covariance_matrix[pd.notna(covariance_matrix['formue_2018_30'])].dropna(axis=1, how='all').iloc[0:3,2:5]

In [23]:
means_data = pd.read_csv("Data/mean_matrix.csv")
covariance_matrix = pd.read_csv("Data/variance_matrix.csv")
means = np.array(means_data[["formue_2018_Mean", "hourly_salary_Mean", "pension_2018_Mean"]])[0]
covar_array = np.array(covariance_matrix.loc[[0, 70, 140], ["formue_2018_30", "hourly_salary_30", "pension_2018_30"]])

In [24]:
covar_array

array([[1.46911229e+11, 4.95039002e+06, 6.02511839e+09],
       [4.95039002e+06, 4.69833979e+03, 1.72700247e+06],
       [6.02511839e+09, 1.72700247e+06, 7.82006946e+09]])

In [8]:
from model import ModelClass

model = ModelClass() # set a few number of periods.

par = model.par
sol = model.sol
sim = model.sim

In [9]:
means_data = pd.read_csv("Data/mean_matrix.csv")
covariance_matrix = pd.read_csv("Data/variance_matrix.csv")

# Concate to the final moments
assets = np.array(means_data["formue_2018_Mean"])
savings = np.array(means_data["pension_2018_Mean"])
hours = np.array(means_data["yearly_hours_Mean"])/par.full_time_hours
mean = np.concatenate([assets, 
                    savings, 
                    hours])
moments = {'assets':assets, 'savings':savings, 'hours':hours}

# Alter covariance matrix to create the final weighting matrix
numeric_cols = covariance_matrix.select_dtypes(include=[np.number]).columns[1:]

row_mask = covariance_matrix["_NAME_"].str.startswith("yearly_hours")
col_mask = [col for col in covariance_matrix.columns if col.startswith("yearly_hours")]

covariance_matrix.loc[row_mask, numeric_cols] = covariance_matrix.loc[row_mask, numeric_cols].astype(float)

covariance_matrix.loc[row_mask, numeric_cols] /= par.full_time_hours

covariance_matrix[col_mask] /= par.full_time_hours

diagonal = np.diag(np.nan_to_num(covariance_matrix[numeric_cols].to_numpy(), nan=0))

weights = 1 / diagonal

C:\Users\B465929\AppData\Local\Temp\ipykernel_17844\156841272.py:27: RuntimeWarning: divide by zero encountered in divide
  weights = 1 / diagonal


In [50]:
diagonal

array([1.46911229e+11, 1.65942896e+11, 1.89399977e+11, 2.02733309e+11,
       2.24423887e+11, 2.48458395e+11, 2.62816790e+11, 2.82810164e+11,
       3.05600861e+11, 3.24912809e+11, 3.49259917e+11, 3.68119347e+11,
       3.88003250e+11, 4.05671916e+11, 4.27422986e+11, 4.40382712e+11,
       4.55482273e+11, 4.70362255e+11, 4.74022847e+11, 4.89120378e+11,
       4.99324410e+11, 5.09470640e+11, 5.20332773e+11, 5.33005513e+11,
       5.38725337e+11, 5.50055657e+11, 5.53942748e+11, 5.60610162e+11,
       5.65811779e+11, 5.71069075e+11, 5.72022272e+11, 5.75611330e+11,
       5.82043442e+11, 5.81040513e+11, 5.80582238e+11, 5.83030407e+11,
       5.88950295e+11, 5.99316246e+11, 5.98954193e+11, 6.01906514e+11,
       6.09798552e+11, 6.07021657e+11, 6.12400813e+11, 6.10273833e+11,
       6.06314129e+11, 6.07422138e+11, 6.10517940e+11, 5.96651296e+11,
       5.88021852e+11, 5.84141484e+11, 5.72086703e+11, 5.68253091e+11,
       5.60434826e+11, 5.48625325e+11, 5.47084749e+11, 5.46896732e+11,
      

In [41]:
weights = np.linalg.inv(np.nan_to_num(covariance_matrix[numeric_cols].to_numpy(), nan=0))

LinAlgError: Singular matrix